### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by tmgldn** [adroitwhiz/css-color#1]
Was about to create this exact project but saw this project on npm that does exactly what I was about to create!

Would you be open to adding me as a collaborator?

* would translate to TypeScript
* could set up with some build tools for releasing to npm to automate the process
* would add some autogenerated docs from typescript

I think this project is an important one, and like you I ended up stumbling on some other worse parsers before finding this one, so want to help it be in a position where more people might find it!

---

unrelated, but the benchmark repo mentioned on the readme is a broken link for me

**Comment by tmgldn** [comment]
Went ahead with a fork and set it up here:

https://github.com/tbjgolden/css-color-l4

**Comment by adroitwhiz** [comment]
It looks like your API surface takes a very different approach from mine--maybe it would be better to release yours as a different package?
